# Generated by Django 2.2 on 2019-04-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('button_link', models.CharField(blank=True, max_length=255, null=True)),
                ('background_image', models.ImageField(upload_to='offer/')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='project/')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='FooterIcons',
            new_name='FooterIcon',
        ),
        migrations.RenameModel(
            old_name='Website_common',
            new_name='WebsiteCommon',
        ),
        migrations.RemoveField(
            model_name='headersection',
            name='button_link',
        ),
    ]
