# Generated by Django 2.2 on 2019-04-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0002_auto_20190412_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersection',
            name='button_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
