# Generated by Django 2.2 on 2019-04-16 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0003_headersection_button_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headersection',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='offersection',
            name='background_image',
        ),
    ]
