# Generated by Django 2.2 on 2019-04-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0004_auto_20190416_0749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutsection',
            old_name='picture',
            new_name='background_picture',
        ),
    ]
