# Generated by Django 2.2 on 2019-04-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0007_auto_20190419_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='offer/'),
        ),
    ]
