# Generated by Django 2.2 on 2019-04-19 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0008_offers_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='icon',
        ),
    ]
