# Generated by Django 2.2 on 2019-04-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0009_remove_offers_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
