# Generated by Django 2.2 on 2019-04-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0010_offers_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitecommon',
            name='offer_background',
            field=models.ImageField(blank=True, null=True, upload_to='offer/'),
        ),
    ]
