# Generated by Django 2.2 on 2019-04-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0011_websitecommon_offer_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='background_image',
        ),
    ]
