# Generated by Django 2.2 on 2019-04-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0012_remove_offers_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('button_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
