# Generated by Django 2.2 on 2019-04-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0013_callsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsection',
            name='main_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='callsection',
            name='text',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
