# Generated by Django 2.2 on 2019-04-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0014_auto_20190422_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsection',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='call/'),
        ),
    ]
