# Generated by Django 2.2 on 2019-04-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0015_callsection_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footericon',
            name='name',
        ),
        migrations.AddField(
            model_name='footericon',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='icon'),
        ),
    ]
