# Generated by Django 2.2 on 2019-04-23 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0016_auto_20190422_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='text',
        ),
    ]
