# Generated by Django 2.2 on 2019-04-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0018_auto_20190424_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callsection',
            name='button_link',
        ),
    ]
