# Generated by Django 2.2 on 2019-04-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0019_remove_callsection_button_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitecommon',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='common/'),
        ),
    ]
