# Generated by Django 2.2 on 2019-04-25 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0020_websitecommon_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitecommon',
            name='background_image',
        ),
    ]
