# Generated by Django 2.2 on 2019-04-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0021_remove_websitecommon_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='offers/'),
        ),
    ]
