# Generated by Django 2.2 on 2019-04-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0022_offers_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='background_image',
        ),
    ]
